# Generated by Django 5.0.4 on 2024-05-03 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('columns', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='column',
            options={},
        ),
    ]
